-- =====================================================================
--  ACAMPAMENTO DESBRAVADORES — ESTRUTURA DO BANCO (Supabase)
--  Rode este arquivo PRIMEIRO no SQL Editor do Supabase.
--  Pode rodar de novo sem problema (não apaga dados).
-- =====================================================================

-- ---------- TABELAS ----------
create table if not exists public.dias (
  id        bigint generated by default as identity primary key,
  data      date   not null,
  rotulo    text   not null,              -- ex.: "Sex 09/10"
  titulo    text   not null,
  subtitulo text   default '',
  ordem     int    default 0
);

create table if not exists public.atividades (
  id          bigint generated by default as identity primary key,
  dia_id      bigint not null references public.dias(id) on delete cascade,
  inicio      text   not null,            -- "HH:MM"
  fim         text   default '',          -- "HH:MM" (opcional)
  titulo      text   not null,
  conducao    text   default '',
  requisitos  text   default '',
  classes     text   default '',          -- ex.: "AM, CO, PE+"
  material    text   default '',
  responsavel text   default '',
  sabado      boolean default false,
  status      text   default 'pendente' check (status in ('pendente','andamento','concluida')),
  ordem       int    default 0
);

create table if not exists public.rodizios (
  id       bigint generated by default as identity primary key,
  dia_id   bigint references public.dias(id) on delete cascade,
  titulo   text   not null,
  horarios jsonb  default '[]'::jsonb,    -- ["14:00–14:40", ...]
  ordem    int    default 0
);

create table if not exists public.estacoes (
  id          bigint generated by default as identity primary key,
  rodizio_id  bigint not null references public.rodizios(id) on delete cascade,
  codigo      text   default '',
  nome        text   not null,
  o_que_fazer text   default '',
  requisitos  text   default '',
  material    text   default '',
  instrutor   text   default '',
  ordem       int    default 0
);

create table if not exists public.requisitos (
  id             bigint generated by default as identity primary key,
  item           text not null,
  tipo           text default 'Requisito',
  quando         text default '',
  classes        text default '',          -- ex.: "AM, CO+" — de qual(is) classe(s) é esse requisito
  guia_instrutor text default '',          -- passo a passo + o que falar, para quem for conduzir
  instrutor      text default '',
  status         text default 'pendente' check (status in ('pendente','andamento','concluida')),
  ordem          int  default 0
);
alter table public.requisitos add column if not exists classes text default '';
alter table public.requisitos add column if not exists guia_instrutor text default '';

create table if not exists public.tarefas (
  id         bigint generated by default as identity primary key,
  fase       text not null default 'ANTES' check (fase in ('ANTES','DEPOIS','FORA')),
  descricao  text not null,
  requisitos text default '',
  feito      boolean default false,
  ordem      int  default 0
);

-- Quem pode editar o site (e-mails dos líderes)
create table if not exists public.editores (
  email text primary key
);

-- ---------- FUNÇÃO: o usuário logado é editor? ----------
create or replace function public.eh_editor()
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (
    select 1 from public.editores
    where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

-- ---------- PERMISSÕES ----------
grant usage on schema public to anon, authenticated;
grant select on public.dias, public.atividades, public.rodizios, public.estacoes,
                public.requisitos, public.tarefas to anon, authenticated;
grant insert, update, delete on public.dias, public.atividades, public.rodizios,
                public.estacoes, public.requisitos, public.tarefas to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.eh_editor() to anon, authenticated;

-- ---------- SEGURANÇA (RLS) ----------
-- Todo mundo pode VER. Só quem está na tabela "editores" pode ALTERAR.
alter table public.editores enable row level security;   -- sem políticas = ninguém lê pela API

do $$
declare t text;
begin
  foreach t in array array['dias','atividades','rodizios','estacoes','requisitos','tarefas'] loop
    execute format('alter table public.%I enable row level security', t);

    execute format('drop policy if exists "leitura publica" on public.%I', t);
    execute format('create policy "leitura publica" on public.%I for select using (true)', t);

    execute format('drop policy if exists "editores inserem" on public.%I', t);
    execute format('create policy "editores inserem" on public.%I for insert to authenticated with check (public.eh_editor())', t);

    execute format('drop policy if exists "editores alteram" on public.%I', t);
    execute format('create policy "editores alteram" on public.%I for update to authenticated using (public.eh_editor()) with check (public.eh_editor())', t);

    execute format('drop policy if exists "editores excluem" on public.%I', t);
    execute format('create policy "editores excluem" on public.%I for delete to authenticated using (public.eh_editor())', t);
  end loop;
end $$;

-- ---------- TEMPO REAL (o site atualiza sozinho quando alguém edita) ----------
do $$
declare t text;
begin
  foreach t in array array['dias','atividades','rodizios','estacoes','requisitos','tarefas'] loop
    begin
      execute format('alter publication supabase_realtime add table public.%I', t);
    exception when duplicate_object then null;  -- já estava adicionada
    end;
  end loop;
end $$;
